name: 'New demo'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      working_directory:
        description: "Terraform working directory (relative to repo root)"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  terraform:
    name: 'create workspace'
    runs-on: ubuntu-latest
    
    container:
      image: hashicorp/terraform:1.9.0

    defaults:
      run:
        working-directory: ${{ github.event.inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4           
        
      - name: Terraform Init
        run: |        
          rm -rf .terraform
          rm -f .terraform.lock.hcl
          # Initialize terraform in the correct directory
          terraform init
        env:       
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          run: terraform plan -input=false -var="tfe_token=${{ secrets.TFE_TOKEN }}"
