name: 'docker workspace init'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      working_directory:
        description: "Terraform working directory (relative to repo root)"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  init:
    name: "Init"
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.9.0    

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4              

      - name: Debug Folder
        run: |
          echo "Scanning directory: ${{ inputs.working_directory }}"
          ls -R 

      - name: Create Backend Config
        run: |
          cat <<EOF > backend.tf
          terraform {
            cloud {
              organization = "UL-ULSE"
              workspaces {
                name = "${{ inputs.environment }}"
              }
            }
          }
          EOF
      
      - name: Terraform Init
        run: terraform init -input=false
        env:
    
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
