name: 'New demo '

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      working_directory:
        description: "Terraform working directory (relative to repo root)"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    # Official Terraform image use kar rahe hain
    container:
      image: hashicorp/terraform:latest
    
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
