name: "docker tf-apply pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      working_directory:
        description: "Terraform working directory"
        required: false
        default: "."
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    runs-on: self-hosted

    container:
      image: hashicorp/terraform:1.9.0

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ inputs.environment }}

      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}

      - name: List files (debug)
        run: ls -R

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
