name: "Docker TFLint"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, qa, prod]
        required: true
      working_directory:
        default: "."
        type: string

jobs:
  tflint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terraform-linters/tflint:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TFLint Init and Run
        run: |
          tflint --init
          tflint --format compact --recursive > tflint-report.txt
        working-directory: ${{ inputs.working_directory }}

      - name: Upload TFLint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}/tflint-report.txt
          if-no-files-found: error
