name: "Docker OPA Policy Validation"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, qa, prod]
        required: true
      working_directory:
        description: "Folder where .tf files exist"
        default: "."
        type: string

jobs:
  opa:
    name: "OPA Validation (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tfplan JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-json-${{ inputs.environment }}-${{ github.run_id }}
          path: ${{ inputs.working_directory }}

      - name: OPA Evaluate (Run inside container)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
          -w /workspace/${{ inputs.working_directory }} \
          openpolicyagent/opa:latest \
          eval --data "/workspace/policies" --input tfplan.json --format json 'data.terraform' > ${{ inputs.working_directory }}/opa-results.json

      - name: Upload OPA results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opa-results-${{ inputs.environment }}-${{ github.run_id }}
          path: ${{ inputs.working_directory }}/opa-results.json
          retention-days: 7
