name: " docker TFSec - Production Secure Scan"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, qa, prod]
        required: true
      working_directory:
        description: "Terraform folder path"
        default: "."
        type: string

jobs:
  tfsec:
    name: "TFSec Scan (${{ inputs.environment }})"
    runs-on: self-hosted

    container:
      image: aquasec/tfsec:v1.28
      options: --user 1000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run TFSec in container
        uses: docker://aquasec/tfsec:v1.28
        with:
          args: ". --format json --soft-fail --out tfsec-report.json"

      - name: GitHub Step Summary
        if: always()
        run: |
          echo "##  TFSec Security Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f "tfsec-report.json" ]; then
            echo "###  JSON Preview (Top 50 lines)" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            head -n 50 tfsec-report.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo " No tfsec report generated" >> $GITHUB_STEP_SUMMARY
          fi
