name: 'docker terraform init'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      working_directory:
        description: "Terraform working directory"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    
    container:
      image: hashicorp/terraform:1.9.0      
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
        
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ inputs.environment }}

      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        
      - name: Generate Plan Summary
        if: always()
        run: |
          echo "### Terraform Plan Summary for ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo '```hcl' >> $GITHUB_STEP_SUMMARY       
          head -c 2000 plan_summary.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "Link to workspace: https://app.terraform.io/app/UL-ULSE/${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}/tfplan
          retention-days: 1
