name: "Docker OPA Pipeline"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, qa, prod]
        required: true
      working_directory:
        description: "Folder where .tf files exist"
        default: "."
        type: string

jobs:
  opa-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List files for debugging
        run: ls -R ${{ inputs.working_directory }}
        
      - name: Download tfplan JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-json-${{ inputs.environment }} # Wahi naam jo upar diya hai
          path: ${{ inputs.working_directory }}

      - name: Run OPA inside Container
        run: |
          docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${{ github.workspace }}:/workspace \
          ghcr.io/aayushsinghal1984/toolimgae:v1 \
          /bin/bash -c "opa eval --data /workspace/policies --input /workspace/${{ inputs.working_directory }}/tfplan.json --format json 'data.terraform' > /workspace/${{ inputs.working_directory }}/opa-results.json"
      - name: Upload OPA results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opa-results-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}/opa-results.json
