name: "docker OPA Pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, qa, prod]
        required: true
      working_directory:
        description: "Folder where .tfplan.json exists"
        default: "."
        type: string

jobs:
  opa:
    runs-on:  ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y curl tar git
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          mv opa /usr/local/bin/

      - name: Evaluate Policy
        run: |
          opa eval \
            --data policies \
            --input tfplan.json \
            --format json \
            "data.azure.naming" > opa-results.json

      - name: Generate Summary
        if: always()
        run: |
          echo "### OPA Validation Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f "opa-results.json" ]; then
            echo "OPA evaluation completed successfully." >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat opa-results.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo " OPA results file not found." >> $GITHUB_STEP_SUMMARY
          fi

     
